#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr desc
#' @importFrom dplyr if_else
#' @importFrom dplyr mutate
#' @importFrom dplyr summarize
#' @importFrom ggplot2 %+replace%
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 annotate
#' @importFrom ggplot2 coord_cartesian
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_line
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_abline
#' @importFrom ggplot2 geom_errorbar
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_ribbon
#' @importFrom ggplot2 geom_segment
#' @importFrom ggplot2 geom_smooth
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 label_parsed
#' @importFrom ggplot2 labeller
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 margin
#' @importFrom ggplot2 scale_alpha_manual
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_colour_brewer
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_shape_manual
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_classic
#' @importFrom ggplot2 unit
#' @importFrom ggplot2 xlab
#' @importFrom glue glue
#' @importFrom purrr list_rbind
#' @importFrom purrr map
#' @importFrom readr read_csv
#' @importFrom readr read_rds
#' @importFrom rlang abort
#' @importFrom rlang have_name
#' @importFrom rlang is_empty
#' @importFrom rlang is_false
#' @importFrom rlang is_true
#' @importFrom rlang set_names
#' @importFrom stats model.matrix
#' @importFrom stats quantile
#' @importFrom tibble as_tibble
#' @importFrom tibble rowid_to_column
#' @importFrom tibble tibble
#' @importFrom tidyselect all_of
#' @importFrom tidyselect any_of
#' @importFrom tidyselect contains
#' @importFrom tidyselect ends_with
#' @importFrom tidyselect matches
#' @importFrom tidyselect starts_with
## usethis namespace: end
NULL
